// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TB_NowyFolder.Data;

#nullable disable

namespace TB_NowyFolder.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251212083732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TB_NowyFolder.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GuestID");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestID = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            GuestID = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "098-765-4321"
                        });
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<int>("GuestID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReservationID");

                    b.HasIndex("GuestID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.ReservationRoom", b =>
                {
                    b.Property<int>("ReservationID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RoomID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReservationID", "RoomID");

                    b.HasIndex("RoomID");

                    b.ToTable("ReservationRooms");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.ReservationService", b =>
                {
                    b.Property<int>("ReservationID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ServiceID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.HasKey("ReservationID", "ServiceID");

                    b.HasIndex("ServiceID");

                    b.ToTable("ReservationServices");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            Capacity = 1,
                            PricePerNight = 100m,
                            RoomNumber = "101",
                            RoomTypeID = 1,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 2,
                            Capacity = 1,
                            PricePerNight = 100m,
                            RoomNumber = "102",
                            RoomTypeID = 1,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 3,
                            Capacity = 2,
                            PricePerNight = 150m,
                            RoomNumber = "201",
                            RoomTypeID = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 4,
                            Capacity = 2,
                            PricePerNight = 150m,
                            RoomNumber = "202",
                            RoomTypeID = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 5,
                            Capacity = 4,
                            PricePerNight = 300m,
                            RoomNumber = "301",
                            RoomTypeID = 3,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("TB_NowyFolder.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Standard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            Description = "Single room with one bed",
                            Standard = "Standard",
                            TypeName = "Single"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            Description = "Double room with two beds",
                            Standard = "Standard",
                            TypeName = "Double"
                        },
                        new
                        {
                            RoomTypeID = 3,
                            Description = "Luxury suite with living area",
                            Standard = "Luxury",
                            TypeName = "Suite"
                        });
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            Availability = "Available",
                            Description = "Continental breakfast",
                            ServiceName = "Breakfast",
                            UnitPrice = 15m
                        },
                        new
                        {
                            ServiceID = 2,
                            Availability = "Available",
                            Description = "24/7 room service",
                            ServiceName = "Room Service",
                            UnitPrice = 25m
                        },
                        new
                        {
                            ServiceID = 3,
                            Availability = "Available",
                            Description = "Relaxing spa treatment",
                            ServiceName = "Spa Treatment",
                            UnitPrice = 80m
                        },
                        new
                        {
                            ServiceID = 4,
                            Availability = "Available",
                            Description = "Transportation to/from airport",
                            ServiceName = "Airport Transfer",
                            UnitPrice = 50m
                        });
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Reservation", b =>
                {
                    b.HasOne("TB_NowyFolder.Models.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.ReservationRoom", b =>
                {
                    b.HasOne("TB_NowyFolder.Models.Reservation", "Reservation")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TB_NowyFolder.Models.Room", "Room")
                        .WithMany("ReservationRooms")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.ReservationService", b =>
                {
                    b.HasOne("TB_NowyFolder.Models.Reservation", "Reservation")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TB_NowyFolder.Models.Service", "Service")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Room", b =>
                {
                    b.HasOne("TB_NowyFolder.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Reservation", b =>
                {
                    b.Navigation("ReservationRooms");

                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Room", b =>
                {
                    b.Navigation("ReservationRooms");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TB_NowyFolder.Models.Service", b =>
                {
                    b.Navigation("ReservationServices");
                });
#pragma warning restore 612, 618
        }
    }
}
